import type { MathArea, MathLesson } from "../math1/types";

type LessonSeed = {
  key: string;
  title: string;
  description: string;
  goals: string[];
  conceptTitle: string;
  body: string[];
  formulas?: string[];
  exampleProblem: string;
  exampleSteps: { expression: string; note: string }[];
  practiceProblem: string;
  practiceAnswers: string[];
  practiceHint: string;
  summary: string[];
};

const makeLesson = (seed: LessonSeed): MathLesson => ({
  key: seed.key,
  title: seed.title,
  description: seed.description,
  goals: seed.goals,
  concepts: [
    {
      title: seed.conceptTitle,
      body: seed.body,
      ...(seed.formulas ? { formulas: seed.formulas } : {}),
    },
  ],
  example: {
    title: `例題: ${seed.title}`,
    problem: seed.exampleProblem,
    steps: seed.exampleSteps,
  },
  practice: {
    title: `練習: ${seed.title}`,
    problem: seed.practiceProblem,
    steps: [
      {
        prompt: "答えを入力してください。",
        answers: seed.practiceAnswers,
        placeholder: "数値には必要な単位も付ける",
      },
    ],
    hint: seed.practiceHint,
  },
  summary: seed.summary,
});

export const physicsFormulaLessonKeys = [
  "planar-vectors",
  "projectile-motion",
  "rigid-body-equilibrium",
  "momentum-impulse",
  "momentum-conservation",
  "collision-energy",
  "uniform-circular-motion",
  "simple-harmonic-motion",
  "kepler-laws",
  "universal-gravitation",
  "kinetic-theory-pressure",
  "ideal-gas-internal-energy",
  "thermodynamic-process",
  "wave-equation-phase",
  "wave-interference-diffraction",
  "sound-interference",
  "doppler-effect",
  "geometrical-optics",
  "light-interference-diffraction",
  "electric-field-coulomb",
  "electric-potential",
  "capacitance",
  "dc-circuits",
  "magnetic-field-current",
  "magnetic-force",
  "electromagnetic-induction",
  "electron-charge-mass",
  "wave-particle-duality",
  "atomic-spectrum",
  "nuclear-physics",
] as const;

export const physicsAreas: MathArea[] = [
  {
    key: "motion",
    title: "様々な運動",
    description:
      "物理基礎の直線運動を発展させ、平面運動、運動量、円運動、万有引力、気体分子運動を系統的に扱います。",
    units: [
      {
        key: "planar-rigid-body",
        title: "平面内の運動と剛体のつり合い",
        description: "ベクトルで平面運動を表し、投射運動と力のモーメントを解析します。",
        lessons: [
          makeLesson({
            key: "planar-vectors",
            title: "曲線運動の速度と加速度",
            description: "変位・速度・加速度をベクトルで表し、成分ごとに平面運動を読み取ります。",
            goals: ["速度と加速度をベクトルとして扱える。", "合成速度と相対速度を成分で求められる。"],
            conceptTitle: "平面運動は成分ごとに解析する",
            body: [
              "平面内の変位、速度、加速度には大きさと向きがあります。x成分とy成分に分けると、各方向の直線運動として同時に解析できます。",
              "観測者が動く場合は、対象の速度から観測者の速度を引いた相対速度で見え方を表します。",
            ],
            formulas: ["v = (vₓ, vᵧ)", "a = Δv / Δt", "v相対 = v対象 − v観測者"],
            exampleProblem: "東向き3.0 m/s、北向き4.0 m/sの速度成分をもつ物体の速さを求める。",
            exampleSteps: [
              { expression: "|v| = √(3.0² + 4.0²)", note: "直交する速度成分なので三平方の関係を使います。" },
              { expression: "|v| = 5.0 m/s", note: "速度ベクトルの大きさが速さです。" },
            ],
            practiceProblem: "東向き6.0 m/s、北向き8.0 m/sの速度成分をもつ物体の速さを求める。",
            practiceAnswers: ["10", "10m/s", "10 m/s"],
            practiceHint: "速度成分6と8を直角三角形の2辺と考えます。",
            summary: ["平面運動の変位・速度・加速度はベクトルで表す。", "成分分解すると各方向を独立に扱える。"],
          }),
          makeLesson({
            key: "projectile-motion",
            title: "水平投射と斜方投射",
            description: "水平方向の等速運動と鉛直方向の等加速度運動を組み合わせて放物運動を解析します。",
            goals: ["水平投射を成分に分けて解析できる。", "斜方投射の速度・位置を時刻の関数で表せる。"],
            conceptTitle: "投射運動では重力は鉛直方向だけに働く",
            body: [
              "空気抵抗を無視すると、水平方向には加速度がなく、鉛直方向には重力加速度gだけが働きます。",
              "初速度を水平・鉛直成分へ分解すると、二つの一次元運動として扱えます。",
            ],
            formulas: ["x = v₀ cosθ · t", "y = v₀ sinθ · t − (1/2)gt²", "vᵧ = v₀ sinθ − gt"],
            exampleProblem: "水平速度10 m/sで投げた物体が2.0 s後に進む水平距離を求める。",
            exampleSteps: [
              { expression: "x = vₓt = 10 × 2.0", note: "水平方向は等速運動です。" },
              { expression: "x = 20 m", note: "鉛直運動とは独立に水平距離を求められます。" },
            ],
            practiceProblem: "水平速度12 m/sで投げた物体が3.0 s後に進む水平距離を求める。",
            practiceAnswers: ["36", "36m", "36 m"],
            practiceHint: "水平方向ではx=vₓtです。",
            summary: ["投射運動は水平・鉛直成分に分ける。", "空気抵抗を無視すれば水平方向は等速、鉛直方向は加速度−gの運動になる。"],
          }),
          makeLesson({
            key: "rigid-body-equilibrium",
            title: "剛体のつり合いと力のモーメント",
            description: "大きさをもつ物体について、並進と回転の両方がつり合う条件を調べます。",
            goals: ["力のモーメントを計算できる。", "剛体のつり合い条件を説明できる。"],
            conceptTitle: "回転しないためにはモーメントもつり合う",
            body: [
              "質点と異なり、剛体では力の合力が0でも回転する場合があります。回転軸から作用線までの垂直距離を使ってモーメントを考えます。",
              "実験では支点からの距離と力の大きさを変え、時計回りと反時計回りのモーメントがつり合う条件を確かめます。",
            ],
            formulas: ["N = Fℓ", "ΣF = 0", "ΣN = 0"],
            exampleProblem: "支点から0.50 mの位置に10 Nの力を垂直に加える。モーメントの大きさを求める。",
            exampleSteps: [
              { expression: "N = Fℓ = 10 × 0.50", note: "力と腕の長さを掛けます。" },
              { expression: "N = 5.0 N·m", note: "回転方向も合わせて判断します。" },
            ],
            practiceProblem: "支点から0.30 mの位置に20 Nの力を垂直に加える。モーメントの大きさを求める。",
            practiceAnswers: ["6", "6N*m", "6 N*m", "6N·m", "6 N·m"],
            practiceHint: "N=Fℓを使います。",
            summary: ["剛体のつり合いには合力0とモーメントの和0の両方が必要。", "重心と支持面の位置関係は転倒条件にも関係する。"],
          }),
        ],
      },
      {
        key: "momentum",
        title: "運動量",
        description: "力積、運動量保存、衝突におけるエネルギー変化を扱います。",
        lessons: [
          makeLesson({
            key: "momentum-impulse",
            title: "運動量と力積",
            description: "運動量の変化と力積の関係をベクトルとして理解します。",
            goals: ["運動量を計算できる。", "力積から運動量の変化を求められる。"],
            conceptTitle: "力を時間にわたって加えると運動量が変わる",
            body: ["運動量pは質量と速度の積で、速度と同じ向きをもつベクトルです。力積は力を加えた時間まで含めて作用を表します。"],
            formulas: ["p = mv", "J = FΔt", "Δp = J"],
            exampleProblem: "質量2.0 kgの物体が3.0 m/sで進むときの運動量を求める。",
            exampleSteps: [{ expression: "p = mv = 2.0 × 3.0 = 6.0 kg·m/s", note: "向きを含めて運動量を表します。" }],
            practiceProblem: "質量4.0 kgの物体が5.0 m/sで進むときの運動量の大きさを求める。",
            practiceAnswers: ["20", "20kg*m/s", "20 kg*m/s", "20kg·m/s", "20 kg·m/s"],
            practiceHint: "p=mvです。",
            summary: ["運動量p=mvはベクトル量。", "力積は運動量の変化に等しい。"],
          }),
          makeLesson({
            key: "momentum-conservation",
            title: "運動量保存の法則",
            description: "衝突や分裂で外力の力積が無視できるときの運動量保存を扱います。",
            goals: ["系を決めて運動量保存を使える。", "二物体の衝突後の速度を求められる。"],
            conceptTitle: "内部力は系全体の運動量を変えない",
            body: ["短い衝突時間に外力の力積が無視できる系では、衝突前後の全運動量が等しくなります。正の向きを決めて速度に符号を付けます。"],
            formulas: ["Σp前 = Σp後"],
            exampleProblem: "2.0 kgの物体が4.0 m/sで進み、静止していた2.0 kgの物体と一体になった。共通速度を求める。",
            exampleSteps: [
              { expression: "2.0×4.0 + 2.0×0 = (2.0+2.0)v", note: "衝突前後の運動量を等しくします。" },
              { expression: "v = 2.0 m/s", note: "完全非弾性衝突では一体になって進みます。" },
            ],
            practiceProblem: "1.0 kgの物体が6.0 m/sで進み、静止した2.0 kgの物体と一体になった。共通速度を求める。",
            practiceAnswers: ["2", "2m/s", "2 m/s"],
            practiceHint: "衝突前の運動量6を全質量3で割ります。",
            summary: ["外力の力積が無視できる系では全運動量が保存する。", "保存則を使う前に系と正方向を決める。"],
          }),
          makeLesson({
            key: "collision-energy",
            title: "衝突と力学的エネルギー",
            description: "はね返り係数を用いて衝突前後の相対速度とエネルギー変化を調べます。",
            goals: ["はね返り係数を使える。", "弾性衝突と非弾性衝突を区別できる。"],
            conceptTitle: "運動量が保存しても運動エネルギーは常に保存するとは限らない",
            body: ["衝突では変形、音、熱などへエネルギーが移るため、運動量保存と運動エネルギー保存を分けて考えます。"],
            formulas: ["e = −(v₂ − v₁)/(u₂ − u₁)", "K = (1/2)mv²"],
            exampleProblem: "固定壁へ速さ5.0 m/sで衝突し、逆向きに4.0 m/sではね返った。はね返り係数を求める。",
            exampleSteps: [{ expression: "e = 4.0/5.0 = 0.80", note: "壁が静止している場合は速さの比で求められます。" }],
            practiceProblem: "固定壁へ速さ10 m/sで衝突し、逆向きに6.0 m/sではね返った。はね返り係数を求める。",
            practiceAnswers: ["0.6", "0.60"],
            practiceHint: "はね返った速さ÷衝突前の速さです。",
            summary: ["はね返り係数は接近速度と分離速度の比。", "完全弾性衝突では運動エネルギーも保存する。"],
          }),
        ],
      },
      {
        key: "circular-oscillation",
        title: "円運動と単振動",
        description: "周期運動を角速度、向心加速度、復元力で記述します。",
        lessons: [
          makeLesson({
            key: "uniform-circular-motion",
            title: "等速円運動",
            description: "角速度、周期、向心加速度、向心力を結び付けます。",
            goals: ["角速度と周期を換算できる。", "向心加速度・向心力を求められる。"],
            conceptTitle: "速さ一定でも速度の向きが変われば加速度がある",
            body: ["等速円運動では速度ベクトルの向きが連続的に変わり、中心向きの加速度が生じます。加速度運動する観測者からは慣性力や遠心力を考える場合があります。"],
            formulas: ["ω = 2π/T", "v = rω", "a = v²/r = rω²", "F = mv²/r"],
            exampleProblem: "半径2.0 mの円を速さ4.0 m/sで等速円運動する物体の向心加速度を求める。",
            exampleSteps: [{ expression: "a = v²/r = 4.0²/2.0 = 8.0 m/s²", note: "速度の向きと直角の中心向き加速度です。" }],
            practiceProblem: "半径5.0 mの円を速さ10 m/sで等速円運動する物体の向心加速度を求める。",
            practiceAnswers: ["20", "20m/s²", "20 m/s²"],
            practiceHint: "a=v²/rです。",
            summary: ["等速円運動には中心向き加速度がある。", "周期・角速度・速さはω=2π/T、v=rωで結ばれる。"],
          }),
          makeLesson({
            key: "simple-harmonic-motion",
            title: "単振動",
            description: "変位に比例する復元力と周期運動を等速円運動と関連付けます。",
            goals: ["単振動の変位・速度・加速度の関係を説明できる。", "ばね振り子と単振り子の周期を扱える。"],
            conceptTitle: "単振動は復元力が変位に比例する運動",
            body: ["つり合い位置からの変位xに比例し逆向きの復元力が働くと、理想的な単振動になります。等速円運動の射影として位置と位相を理解できます。"],
            formulas: ["a = −ω²x", "Tばね = 2π√(m/k)", "T単振り子 = 2π√(ℓ/g)"],
            exampleProblem: "周期2.0 sの単振動の角振動数ωを求める。",
            exampleSteps: [{ expression: "ω = 2π/T = 2π/2.0 = π rad/s", note: "1周期で位相が2π進みます。" }],
            practiceProblem: "周期4.0 sの単振動の角振動数ωを求める。",
            practiceAnswers: ["π/2", "0.5π", "π/2rad/s", "π/2 rad/s"],
            practiceHint: "ω=2π/Tです。",
            summary: ["単振動では加速度が変位に比例し逆向き。", "ばね振り子・単振り子の周期は振動条件から決まる。"],
          }),
        ],
      },
      {
        key: "gravitation",
        title: "万有引力",
        description: "惑星の観測法則と万有引力を結び、天体・人工衛星の運動を説明します。",
        lessons: [
          makeLesson({
            key: "kepler-laws",
            title: "惑星の運動とケプラーの法則",
            description: "観測資料から惑星軌道、面積速度、周期の規則性を読み取ります。",
            goals: ["ケプラーの三法則を説明できる。", "周期と軌道半径の関係を利用できる。"],
            conceptTitle: "惑星の運動には観測から見いだされた規則性がある",
            body: ["惑星は太陽を一焦点とする楕円軌道を描き、面積速度が一定です。同じ中心天体を回る惑星では周期の2乗と軌道長半径の3乗の比が一定です。"],
            formulas: ["T²/a³ = 一定"],
            exampleProblem: "同じ恒星を回る惑星AとBで、軌道長半径の比aB/aA=4のとき周期比TB/TAを求める。",
            exampleSteps: [{ expression: "(TB/TA)² = 4³ = 64 ⇒ TB/TA = 8", note: "ケプラー第3法則を比で使います。" }],
            practiceProblem: "軌道長半径の比aB/aA=9のとき周期比TB/TAを求める。",
            practiceAnswers: ["27"],
            practiceHint: "周期比は軌道長半径比の3/2乗です。",
            summary: ["ケプラーの法則は惑星観測から得られた規則性。", "同じ中心天体ならT²/a³が一定。"],
          }),
          makeLesson({
            key: "universal-gravitation",
            title: "万有引力と重力による位置エネルギー",
            description: "万有引力の法則から天体・人工衛星の運動と位置エネルギーを扱います。",
            goals: ["二物体間の万有引力を求められる。", "万有引力による位置エネルギーの符号を説明できる。"],
            conceptTitle: "質量をもつ物体は互いに引き合う",
            body: ["万有引力は二つの質量の積に比例し、中心間距離の2乗に反比例します。無限遠を位置エネルギー0とすると、引力で束縛された状態の位置エネルギーは負です。"],
            formulas: ["F = GmM/r²", "U = −GmM/r"],
            exampleProblem: "距離rが2倍になると、他条件が同じとき万有引力は何倍になるか。",
            exampleSteps: [{ expression: "F ∝ 1/r² ⇒ 1/2² = 1/4", note: "逆2乗則を使います。" }],
            practiceProblem: "距離rが3倍になると万有引力は何倍になるか。",
            practiceAnswers: ["1/9", "9分の1"],
            practiceHint: "距離の2乗に反比例します。",
            summary: ["万有引力は距離の2乗に反比例する。", "万有引力による位置エネルギーは無限遠基準で負になる。"],
          }),
        ],
      },
      {
        key: "kinetic-theory",
        title: "気体分子の運動",
        description: "分子運動から圧力・温度・内部エネルギーを理解し、熱力学第一法則へつなげます。",
        lessons: [
          makeLesson({
            key: "kinetic-theory-pressure",
            title: "気体分子の運動と圧力",
            description: "理想気体の状態方程式と分子運動から圧力・温度を結び付けます。",
            goals: ["理想気体の状態方程式を使える。", "平均運動エネルギーと絶対温度の関係を説明できる。"],
            conceptTitle: "圧力は分子が壁へ運動量を渡す結果",
            body: ["多数の分子が容器の壁へ衝突して運動量を変えることで巨視的な圧力が生じます。理想気体では状態量p、V、n、Tが一つの式で結ばれます。"],
            formulas: ["pV = nRT", "平均並進運動エネルギー = (3/2)kT"],
            exampleProblem: "物質量1.0 mol、温度300 Kの理想気体についてpVをR=8.31 J/(mol·K)として求める。",
            exampleSteps: [{ expression: "pV = nRT = 1.0×8.31×300 = 2.49×10³ J", note: "Pa·m³はJと同じ次元です。" }],
            practiceProblem: "物質量2.0 mol、温度300 Kの理想気体のpVをR=8.31として求める。",
            practiceAnswers: ["4986", "4.986*10^3", "4.99*10^3", "4986J", "4986 J"],
            practiceHint: "pV=nRTです。",
            summary: ["理想気体ではpV=nRTが成り立つ。", "分子の平均運動エネルギーは絶対温度に比例する。"],
          }),
          makeLesson({
            key: "ideal-gas-internal-energy",
            title: "理想気体の内部エネルギー",
            description: "分子運動と温度から理想気体の内部エネルギーを理解します。",
            goals: ["内部エネルギーと温度の関係を説明できる。", "単原子分子理想気体の内部エネルギーを計算できる。"],
            conceptTitle: "理想気体の内部エネルギーは分子の運動エネルギーの総和",
            body: ["単原子分子理想気体では分子間相互作用の位置エネルギーを無視できるため、内部エネルギーは絶対温度だけで決まります。"],
            formulas: ["U = (3/2)nRT", "ΔU = (3/2)nRΔT"],
            exampleProblem: "1.0 molの単原子分子理想気体を10 K昇温したときの内部エネルギー増加をR=8.31として求める。",
            exampleSteps: [{ expression: "ΔU = (3/2)×1.0×8.31×10 ≈ 125 J", note: "単原子分子理想気体の式を使います。" }],
            practiceProblem: "2.0 molの単原子分子理想気体を10 K昇温したときの内部エネルギー増加をR=8.31として求める。",
            practiceAnswers: ["249.3", "249", "249J", "249 J", "249.3J", "249.3 J"],
            practiceHint: "ΔU=(3/2)nRΔTです。",
            summary: ["単原子分子理想気体の内部エネルギーは絶対温度に比例する。", "温度変化からΔUを求められる。"],
          }),
          makeLesson({
            key: "thermodynamic-process",
            title: "気体の状態変化と熱力学第一法則",
            description: "熱、仕事、内部エネルギーの変化をエネルギー保存として扱います。",
            goals: ["熱力学第一法則を符号に注意して使える。", "p-V図から気体のする仕事を解釈できる。"],
            conceptTitle: "熱と仕事は内部エネルギーを変える二つの経路",
            body: ["気体へ加えた熱量Qは内部エネルギーの増加と気体が外部へした仕事に分配されます。状態変化の種類によってQ、W、ΔUの関係が変わります。"],
            formulas: ["Q = ΔU + W", "W = ∫p dV"],
            exampleProblem: "気体へ500 Jの熱を加え、気体が外部へ200 Jの仕事をした。内部エネルギーの増加を求める。",
            exampleSteps: [{ expression: "ΔU = Q − W = 500 − 200 = 300 J", note: "気体がした仕事を正として扱います。" }],
            practiceProblem: "気体へ800 Jの熱を加え、気体が外部へ300 Jの仕事をした。内部エネルギーの増加を求める。",
            practiceAnswers: ["500", "500J", "500 J"],
            practiceHint: "Q=ΔU+WをΔUについて解きます。",
            summary: ["熱力学第一法則はエネルギー保存を気体へ適用したもの。", "p-V図の面積は準静的変化で気体がする仕事に対応する。"],
          }),
        ],
      },
    ],
  },
  {
    key: "waves",
    title: "波",
    description: "波の式・干渉・回折、音のドップラー効果、光の幾何光学と波動性を扱います。",
    units: [
      {
        key: "wave-propagation",
        title: "波の伝わり方",
        description: "正弦波、位相、ホイヘンスの原理、干渉・回折を学びます。",
        lessons: [
          makeLesson({
            key: "wave-equation-phase",
            title: "波の式・位相・ホイヘンスの原理",
            description: "正弦波を位置と時刻の関数で表し、波面の伝わり方を理解します。",
            goals: ["進行波の式から振幅・波長・周期を読み取れる。", "ホイヘンスの原理で反射・屈折を説明できる。"],
            conceptTitle: "波形は位相が空間を伝わる",
            body: ["正弦波では振動の状態を位相で表します。ホイヘンスの原理では各波面上の点を新しい波源とみなし、次の波面を考えます。"],
            formulas: ["y = A sin 2π(t/T − x/λ)", "v = fλ"],
            exampleProblem: "波長2.0 m、振動数3.0 Hzの波の速さを求める。",
            exampleSteps: [{ expression: "v = fλ = 3.0×2.0 = 6.0 m/s", note: "1秒あたり3波長進みます。" }],
            practiceProblem: "波長0.50 m、振動数8.0 Hzの波の速さを求める。",
            practiceAnswers: ["4", "4m/s", "4 m/s"],
            practiceHint: "v=fλです。",
            summary: ["正弦波の式では位相が位置と時刻で変化する。", "ホイヘンスの原理は反射・屈折・回折を統一的に考える手掛かりになる。"],
          }),
          makeLesson({
            key: "wave-interference-diffraction",
            title: "水面波の干渉と回折",
            description: "二つの波源による干渉条件と、障害物・開口での回折を扱います。",
            goals: ["経路差から強め合い・弱め合いを判定できる。", "回折が顕著になる条件を説明できる。"],
            conceptTitle: "重ね合わせにより空間に強弱の分布ができる",
            body: ["同位相の二波では経路差が波長の整数倍なら強め合い、半整数倍なら弱め合います。波長と開口幅が同程度になると回折が目立ちます。"],
            formulas: ["強め合い: ΔL = mλ", "弱め合い: ΔL = (m + 1/2)λ"],
            exampleProblem: "波長0.40 mの同位相二波で経路差0.80 mの点は強め合うか。",
            exampleSteps: [{ expression: "ΔL/λ = 0.80/0.40 = 2", note: "整数なので強め合います。" }],
            practiceProblem: "波長0.30 m、経路差0.45 mの点は強め合い・弱め合いのどちらか。",
            practiceAnswers: ["弱め合い", "弱めあい"],
            practiceHint: "0.45/0.30=1.5です。",
            summary: ["干渉条件は経路差と波長で判断する。", "回折は波長が開口・障害物の大きさと同程度のとき顕著。"],
          }),
        ],
      },
      {
        key: "sound",
        title: "音",
        description: "音の干渉・回折と、音源・観測者の運動によるドップラー効果を扱います。",
        lessons: [
          makeLesson({
            key: "sound-interference",
            title: "音の干渉・回折と周波数分析",
            description: "音波の重ね合わせ、回折、波形・周波数成分と音色を理解します。",
            goals: ["音の干渉・回折を波の性質として説明できる。", "周波数成分と音色の関係を説明できる。"],
            conceptTitle: "音も波なので干渉・回折する",
            body: ["二つの音波が重なると位置によって強弱が生じます。音は障害物の背後へ回り込み、複雑な音は基本周波数と倍音などの周波数成分に分けて考えられます。"],
            formulas: ["うなりの振動数 fB = |f₁ − f₂|"],
            exampleProblem: "440 Hzと444 Hzの音を同時に鳴らす。1秒あたりのうなり回数を求める。",
            exampleSteps: [{ expression: "fB = |444−440| = 4 Hz", note: "近い振動数の差がうなりの振動数です。" }],
            practiceProblem: "500 Hzと506 Hzの音を同時に鳴らす。うなりの振動数を求める。",
            practiceAnswers: ["6", "6Hz", "6 Hz"],
            practiceHint: "二つの振動数の差の絶対値です。",
            summary: ["音も重ね合わせにより干渉する。", "音色は周波数成分の組合せと強さに関係する。"],
          }),
          makeLesson({
            key: "doppler-effect",
            title: "音のドップラー効果",
            description: "音源と観測者の運動による観測振動数の変化を扱います。",
            goals: ["音源・観測者の移動方向から振動数変化を予測できる。", "同一直線上のドップラー効果を計算できる。"],
            conceptTitle: "音源の運動は波長を変え、観測者の運動は波面に出会う頻度を変える",
            body: ["音源が観測者へ近づくと前方の波長が短くなります。観測者が音源へ近づくと単位時間に出会う波面が増えます。符号は『近づくと振動数が高くなる』ことを基準に確認します。"],
            formulas: ["f′ = (V ± vo)/(V ∓ vs) · f"],
            exampleProblem: "静止観測者に向かって音源が動くと、観測振動数は元の振動数より高いか低いか。",
            exampleSteps: [{ expression: "音源前方では波長が短くなる ⇒ f′は高くなる", note: "波の速さがほぼ一定なのでv=fλから判断できます。" }],
            practiceProblem: "音源から遠ざかる静止観測者が聞く振動数は、元の振動数より高いか低いか。",
            practiceAnswers: ["低い", "低くなる", "小さい"],
            practiceHint: "波面に出会う回数が減ります。",
            summary: ["近づく運動は観測振動数を高くし、遠ざかる運動は低くする。", "音速を基準に音源速度と観測者速度を区別する。"],
          }),
        ],
      },
      {
        key: "light",
        title: "光",
        description: "反射・屈折・分散・偏光、鏡・レンズ、ヤングの実験・回折格子・薄膜干渉を学びます。",
        lessons: [
          makeLesson({
            key: "geometrical-optics",
            title: "光の伝わり方と幾何光学",
            description: "光の速さ、屈折、分散、偏光、鏡・レンズの基本を扱います。",
            goals: ["屈折の法則を使える。", "レンズによる像を基本的な光線図で説明できる。"],
            conceptTitle: "媒質が変わると光の速さと進行方向が変わる",
            body: ["屈折率は真空中の光速と媒質中の光速の比です。境界面では振動数が保たれ、速さの変化に応じて波長が変わります。偏光は光が横波であることを示します。"],
            formulas: ["n = c/v", "n₁ sinθ₁ = n₂ sinθ₂", "1/a + 1/b = 1/f"],
            exampleProblem: "真空中の光速3.0×10⁸ m/s、媒質中2.0×10⁸ m/sのとき屈折率を求める。",
            exampleSteps: [{ expression: "n = c/v = 3.0/2.0 = 1.5", note: "同じ単位なので10⁸は約分できます。" }],
            practiceProblem: "媒質中の光速が1.5×10⁸ m/sのとき屈折率を求める。c=3.0×10⁸ m/sとする。",
            practiceAnswers: ["2", "2.0"],
            practiceHint: "n=c/vです。",
            summary: ["屈折率は光速の比で定義する。", "分散・偏光・レンズの性質を光の伝わり方と関連付ける。"],
          }),
          makeLesson({
            key: "light-interference-diffraction",
            title: "光の回折と干渉",
            description: "ヤングの実験、回折格子、薄膜干渉を光波の位相と経路差で扱います。",
            goals: ["ヤングの干渉縞の間隔を求められる。", "薄膜干渉で反射による位相変化を考慮できる。"],
            conceptTitle: "光でも経路差が位相差となって干渉縞を作る",
            body: ["光の干渉では経路長の差に加えて、反射時の位相のずれが重要です。複スリットや回折格子では波長を干渉縞から測定できます。"],
            formulas: ["ヤング: Δx = λL/d", "回折格子: d sinθ = mλ"],
            exampleProblem: "λ=600 nm、L=2.0 m、d=0.50 mmのヤングの実験で縞間隔を求める。",
            exampleSteps: [{ expression: "Δx = λL/d = 600×10⁻9×2.0/(0.50×10⁻3) = 2.4×10⁻3 m", note: "単位をmにそろえます。" }],
            practiceProblem: "λ=500 nm、L=1.0 m、d=0.50 mmのヤングの実験で縞間隔を求める。",
            practiceAnswers: ["0.001", "1.0*10^-3", "1mm", "1 mm"],
            practiceHint: "Δx=λL/dで、nmとmmをmへ直します。",
            summary: ["光の干渉条件は経路差と位相差で決まる。", "ヤングの実験・回折格子・薄膜干渉は光の波動性を示す。"],
          }),
        ],
      },
    ],
  },
  {
    key: "electricity-magnetism",
    title: "電気と磁気",
    description: "電荷と電界、電位、コンデンサー、直流回路、磁界、ローレンツ力、電磁誘導、電磁波を扱います。",
    units: [
      {
        key: "electricity-current",
        title: "電気と電流",
        description: "静電気力から電界・電位・電気容量へ進み、直流回路の基本法則を学びます。",
        lessons: [
          makeLesson({
            key: "electric-field-coulomb",
            title: "電荷と電界",
            description: "クーロン力、電界、電気力線、静電誘導を扱います。",
            goals: ["点電荷間の静電気力を求められる。", "電界を単位正電荷あたりの力として説明できる。"],
            conceptTitle: "電界は電荷が周囲の空間につくる力の場",
            body: ["クーロン力は電荷の積に比例し、距離の2乗に反比例します。電界を導入すると、試験電荷を置く前から空間の各点の性質として力を表せます。"],
            formulas: ["F = kq₁q₂/r²", "E = F/q = kQ/r²"],
            exampleProblem: "同じ二電荷間の距離を2倍にすると静電気力は何倍になるか。",
            exampleSteps: [{ expression: "F ∝ 1/r² ⇒ 1/4", note: "クーロン力は逆2乗則です。" }],
            practiceProblem: "二電荷間の距離を3倍にすると静電気力は何倍になるか。",
            practiceAnswers: ["1/9", "9分の1"],
            practiceHint: "距離の2乗に反比例します。",
            summary: ["クーロン力は電荷の積に比例し距離の2乗に反比例する。", "電界は単位正電荷あたりの力で定義する。"],
          }),
          makeLesson({
            key: "electric-potential",
            title: "電界と電位",
            description: "静電気力による位置エネルギーと電位・電位差を関連付けます。",
            goals: ["電位を単位電荷あたりの位置エネルギーとして説明できる。", "一様電界で電位差と電界を結び付けられる。"],
            conceptTitle: "電位は電気的な位置エネルギーを電荷1 Cあたりで表した量",
            body: ["電位差は正電荷を移動させるときのエネルギー変化を表します。電界は電位が最も急に下がる方向を向きます。"],
            formulas: ["V = U/q", "ΔU = qΔV", "一様電界: E = V/d"],
            exampleProblem: "2.0 Cの電荷が10 Vの電位差を移動して位置エネルギーが変化する大きさを求める。",
            exampleSteps: [{ expression: "|ΔU| = q|ΔV| = 2.0×10 = 20 J", note: "向きによる符号は移動方向と電荷の符号で決めます。" }],
            practiceProblem: "0.50 Cの電荷が12 Vの電位差を移動したときの位置エネルギー変化の大きさを求める。",
            practiceAnswers: ["6", "6J", "6 J"],
            practiceHint: "|ΔU|=|qΔV|です。",
            summary: ["電位は単位電荷あたりの位置エネルギー。", "電界と電位は空間的な変化率で結ばれる。"],
          }),
          makeLesson({
            key: "capacitance",
            title: "コンデンサーと電気容量",
            description: "電荷を蓄える仕組み、電気容量、接続、蓄えられるエネルギーを扱います。",
            goals: ["Q=CVを使える。", "コンデンサーに蓄えられるエネルギーを求められる。"],
            conceptTitle: "電気容量は電位差1 Vあたりに蓄えられる電荷量",
            body: ["平行板コンデンサーでは極板面積を大きく、間隔を小さくすると電気容量が大きくなります。直列・並列接続では電荷と電圧の分配を考えます。"],
            formulas: ["Q = CV", "U = (1/2)CV²", "C = εS/d"],
            exampleProblem: "電気容量20 μFのコンデンサーに10 Vを加えたときの電荷量を求める。",
            exampleSteps: [{ expression: "Q=CV=20×10⁻6×10=2.0×10⁻4 C", note: "μFをFへ換算します。" }],
            practiceProblem: "電気容量50 μFのコンデンサーに4.0 Vを加えたときの電荷量を求める。",
            practiceAnswers: ["2*10^-4", "0.0002", "2*10^-4C", "0.0002C"],
            practiceHint: "Q=CVで、μ=10⁻6です。",
            summary: ["電気容量CはQ/V。", "コンデンサーは電界のエネルギーを蓄える。"],
          }),
          makeLesson({
            key: "dc-circuits",
            title: "直流回路・内部抵抗・半導体",
            description: "キルヒホッフの法則、電池の内部抵抗、抵抗率の温度変化、半導体を扱います。",
            goals: ["複数の枝をもつ直流回路をキルヒホッフの法則で解析できる。", "起電力と端子電圧の違いを説明できる。"],
            conceptTitle: "回路では電荷保存とエネルギー保存が同時に成り立つ",
            body: ["分岐点では流入電流と流出電流が等しく、閉回路では電位差の総和が0になります。電池には内部抵抗があり、電流が流れると端子電圧が起電力より小さくなる場合があります。"],
            formulas: ["分岐則: ΣI入 = ΣI出", "閉路則: ΣΔV = 0", "V端子 = E − rI"],
            exampleProblem: "起電力12 V、内部抵抗1.0 Ωの電池から2.0 A流れる。端子電圧を求める。",
            exampleSteps: [{ expression: "V = E−rI = 12−1.0×2.0 = 10 V", note: "内部抵抗で2 V低下します。" }],
            practiceProblem: "起電力9.0 V、内部抵抗0.50 Ωの電池から2.0 A流れる。端子電圧を求める。",
            practiceAnswers: ["8", "8V", "8 V"],
            practiceHint: "V=E−rIです。",
            summary: ["キルヒホッフの法則は電荷保存・エネルギー保存を回路に適用したもの。", "内部抵抗がある電池の端子電圧は電流で変化する。"],
          }),
        ],
      },
      {
        key: "current-magnetic-field",
        title: "電流と磁界",
        description: "電流がつくる磁界、磁界中の力、電磁誘導、交流、電磁波を学びます。",
        lessons: [
          makeLesson({
            key: "magnetic-field-current",
            title: "電流がつくる磁界",
            description: "直線電流、円形電流、ソレノイドがつくる磁界を扱います。",
            goals: ["右ねじの規則で磁界の向きを判断できる。", "直線電流がつくる磁束密度を計算できる。"],
            conceptTitle: "電流の周囲には磁界が生じる",
            body: ["磁界の向きは電流の向きと幾何学的に結び付きます。直線電流から遠ざかるほど磁界は弱くなります。"],
            formulas: ["直線電流: B = μ₀I/(2πr)", "ソレノイド: B = μ₀nI"],
            exampleProblem: "直線電流からの距離を2倍にすると、同じ電流で磁束密度は何倍になるか。",
            exampleSteps: [{ expression: "B ∝ 1/r ⇒ 1/2", note: "直線電流の磁界は距離に反比例します。" }],
            practiceProblem: "直線電流からの距離を4倍にすると磁束密度は何倍になるか。",
            practiceAnswers: ["1/4", "4分の1"],
            practiceHint: "Bはrに反比例します。",
            summary: ["電流は周囲に磁界をつくる。", "磁界の向きは右ねじの規則で判断する。"],
          }),
          makeLesson({
            key: "magnetic-force",
            title: "電流が磁界から受ける力とローレンツ力",
            description: "電流・荷電粒子が磁界から受ける力を方向と大きさの両面で扱います。",
            goals: ["電流が受ける磁気力を求められる。", "ローレンツ力による荷電粒子の円運動を説明できる。"],
            conceptTitle: "磁気力は運動方向を曲げるが速さを変えない場合がある",
            body: ["磁界中を動く電荷は速度と磁界の両方に垂直な力を受けます。速度に常に垂直なら仕事をせず、速さを変えずに進行方向だけを変えます。"],
            formulas: ["F = BIl sinθ", "F = qvB sinθ", "qvB = mv²/r"],
            exampleProblem: "B=0.50 Tの磁界に垂直な長さ0.20 mの導線へ4.0 A流す。力を求める。",
            exampleSteps: [{ expression: "F=BIl=0.50×4.0×0.20=0.40 N", note: "導線と磁界が垂直なのでsinθ=1です。" }],
            practiceProblem: "B=0.20 T、I=5.0 A、l=0.30 mで互いに垂直なとき力を求める。",
            practiceAnswers: ["0.3", "0.30", "0.3N", "0.30 N"],
            practiceHint: "F=BIlです。",
            summary: ["磁界中の電流・運動電荷は磁気力を受ける。", "速度に垂直なローレンツ力は円運動の向心力になり得る。"],
          }),
          makeLesson({
            key: "electromagnetic-induction",
            title: "電磁誘導・自己誘導・交流",
            description: "磁束変化による誘導起電力、レンツの法則、自己・相互誘導、交流回路の基礎を扱います。",
            goals: ["ファラデーの電磁誘導の法則を使える。", "誘導起電力の向きをレンツの法則で判断できる。"],
            conceptTitle: "磁束の変化を妨げる向きに誘導電流が流れる",
            body: ["コイルを貫く磁束が時間変化すると誘導起電力が生じます。負号は変化を打ち消す向きに誘導が起こることを表します。交流ではコイルとコンデンサーのリアクタンスが振動数で変化します。"],
            formulas: ["e = −N ΔΦ/Δt", "Φ = BS cosθ", "XL = ωL", "XC = 1/(ωC)"],
            exampleProblem: "1巻きコイルの磁束が0.20 sで0.10 Wb変化した。誘導起電力の大きさを求める。",
            exampleSteps: [{ expression: "|e| = |ΔΦ/Δt| = 0.10/0.20 = 0.50 V", note: "向きはレンツの法則で別に判断します。" }],
            practiceProblem: "20巻きコイルで1巻きあたりの磁束が0.050 sで0.0020 Wb変化した。誘導起電力の大きさを求める。",
            practiceAnswers: ["0.8", "0.80", "0.8V", "0.80 V"],
            practiceHint: "|e|=N|ΔΦ|/Δtです。",
            summary: ["磁束変化が誘導起電力を生む。", "交流ではLとCの応答が振動数に依存する。"],
          }),
          makeLesson({
            key: "electromagnetic-waves",
            title: "電磁波の発生・性質・利用",
            description: "電気振動から電磁波が生じることと、電波からX線までの利用を理解します。",
            goals: ["電磁波が電界と磁界の変化として伝わることを説明できる。", "周波数帯による代表的な利用例を挙げられる。"],
            conceptTitle: "時間変化する電界と磁界が空間を伝わる",
            body: ["電磁波は真空中でも伝わり、光も電磁波の一種です。周波数と波長によって電波、赤外線、可視光、紫外線、X線などに分類され、性質に応じて通信・加熱・観測・医療などに利用されます。"],
            exampleProblem: "可視光は電磁波か、力学的な媒質波か。",
            exampleSteps: [{ expression: "可視光は電磁波", note: "真空中でも伝わり、電界と磁界の変化として記述されます。" }],
            practiceProblem: "真空中で電磁波が伝わるために物質の媒質は必要か。",
            practiceAnswers: ["不要", "必要ない", "いらない"],
            practiceHint: "宇宙空間を太陽光が伝わることを考えます。",
            summary: ["電磁波は真空中を伝わる。", "周波数帯ごとの性質を利用して通信・観測・医療などに使われる。"],
          }),
        ],
      },
    ],
  },
  {
    key: "atoms",
    title: "原子",
    description: "電子と光の粒子性・波動性、原子スペクトル、原子核、素粒子、物理学が築く未来を学びます。",
    units: [
      {
        key: "electron-light",
        title: "電子と光",
        description: "電子の電荷・質量と、光・電子の粒子性と波動性を歴史的実験と結び付けます。",
        lessons: [
          makeLesson({
            key: "electron-charge-mass",
            title: "電子の電荷と質量",
            description: "比電荷や電気素量の測定を通して電子の基本量を理解します。",
            goals: ["電子の比電荷の意味を説明できる。", "電気素量と電子1個の電荷を関連付けられる。"],
            conceptTitle: "電子の存在は真空放電などの実験から確立された",
            body: ["陰極線の電界・磁界による曲がりから比電荷e/mを測定でき、ミリカンの油滴実験などから電気素量eを求めることで電子の質量が分かります。"],
            formulas: ["e/m = 電子の比電荷", "q電子 = −e"],
            exampleProblem: "電子3個がもつ電荷を電気素量eで表す。",
            exampleSteps: [{ expression: "q = −3e", note: "電子1個は−eの電荷をもちます。" }],
            practiceProblem: "電子5個がもつ電荷を電気素量eで表す。",
            practiceAnswers: ["-5e", "−5e"],
            practiceHint: "電子1個は−eです。",
            summary: ["電子は負の電気素量−eをもつ。", "比電荷と電気素量の測定から電子の質量を決定できる。"],
          }),
          makeLesson({
            key: "wave-particle-duality",
            title: "光と電子の粒子性・波動性",
            description: "光電効果、光量子、電子線回折、物質波、X線を扱います。",
            goals: ["光電効果を光量子仮説で説明できる。", "電子の物質波の波長を説明できる。"],
            conceptTitle: "光も物質も実験条件により粒子的・波動的な性質を示す",
            body: ["光電効果は光のエネルギーが振動数に比例する光量子として物質へ渡ることを示します。電子線回折は電子にも波長を対応させられることを示します。"],
            formulas: ["E光子 = hf", "Kmax = hf − W", "λ = h/p"],
            exampleProblem: "振動数fの光子1個のエネルギーを表す式を答える。",
            exampleSteps: [{ expression: "E = hf", note: "比例定数hがプランク定数です。" }],
            practiceProblem: "運動量pをもつ粒子に対応するド・ブロイ波長を表す式を答える。",
            practiceAnswers: ["h/p", "λ=h/p", "lambda=h/p"],
            practiceHint: "波長は運動量に反比例します。",
            summary: ["光電効果は光の粒子性を示す。", "電子線回折は電子の波動性を示す。"],
          }),
        ],
      },
      {
        key: "atom-nucleus",
        title: "原子と原子核",
        description: "原子スペクトルとエネルギー準位、原子核反応、素粒子を扱います。",
        lessons: [
          makeLesson({
            key: "atomic-spectrum",
            title: "原子の構造とスペクトル",
            description: "水素原子のエネルギー準位と発光・吸収スペクトルの関係を学びます。",
            goals: ["線スペクトルとエネルギー準位を関連付けられる。", "光子のエネルギーから準位差を求められる。"],
            conceptTitle: "原子の電子エネルギーは連続ではなく離散的",
            body: ["原子がある準位から別の準位へ遷移すると、準位差に等しいエネルギーの光子を放出・吸収します。水素原子のスペクトル系列はこの量子化を反映します。"],
            formulas: ["hf = |E₂ − E₁|", "水素原子: En = −13.6/n² eV"],
            exampleProblem: "エネルギー差2.0 eVの遷移で放出される光子のエネルギーは何eVか。",
            exampleSteps: [{ expression: "E光子 = |ΔE| = 2.0 eV", note: "準位差がそのまま光子エネルギーになります。" }],
            practiceProblem: "エネルギー差3.4 eVの遷移で放出される光子のエネルギーは何eVか。",
            practiceAnswers: ["3.4", "3.4eV", "3.4 eV"],
            practiceHint: "光子エネルギーは準位差です。",
            summary: ["線スペクトルは原子の離散的エネルギー準位を反映する。", "遷移で放出・吸収する光子はhf=|ΔE|を満たす。"],
          }),
          makeLesson({
            key: "nuclear-physics",
            title: "原子核・崩壊・核反応",
            description: "原子核の構成、半減期、核分裂・核融合、質量とエネルギーの等価性を扱います。",
            goals: ["半減期から残存量を求められる。", "質量欠損と放出エネルギーを関連付けられる。"],
            conceptTitle: "原子核反応では質量差がエネルギーとして現れる",
            body: ["放射性核種の崩壊は確率的ですが、多数集まると半減期で指数関数的に減少します。核分裂・核融合では結合エネルギーの差によりエネルギーが放出されます。"],
            formulas: ["N = N₀(1/2)^(t/T)", "E = mc²"],
            exampleProblem: "半減期10年の核種が20年後に残る割合を求める。",
            exampleSteps: [{ expression: "(1/2)^(20/10) = (1/2)² = 1/4", note: "2回の半減期が経過しています。" }],
            practiceProblem: "半減期5年の核種が15年後に残る割合を求める。",
            practiceAnswers: ["1/8", "8分の1", "0.125"],
            practiceHint: "15/5=3回の半減期です。",
            summary: ["半減期で放射性核種の個数は指数関数的に減る。", "核反応では質量とエネルギーの等価性が重要。"],
          }),
          makeLesson({
            key: "elementary-particles",
            title: "素粒子と基本的な力",
            description: "クォーク、レプトンなどの素粒子と、基本的な相互作用の存在を概観します。",
            goals: ["物質を構成する素粒子の例を挙げられる。", "高エネルギー実験が素粒子研究に必要な理由を説明できる。"],
            conceptTitle: "原子核より小さい階層にも構造がある",
            body: ["陽子・中性子はクォークから構成され、電子やニュートリノはレプトンに分類されます。粒子の生成・反応を調べる高エネルギー実験は物質の基本構造を探る方法です。相対論的効果にも定性的に触れます。"],
            exampleProblem: "電子はクォークとレプトンのどちらに分類されるか。",
            exampleSteps: [{ expression: "電子はレプトン", note: "電子は内部構造が確認されていない基本粒子として扱われます。" }],
            practiceProblem: "ニュートリノはクォークとレプトンのどちらに分類されるか。",
            practiceAnswers: ["レプトン"],
            practiceHint: "電子と同じ分類です。",
            summary: ["クォークとレプトンは代表的な素粒子の分類。", "高エネルギー実験で短い距離スケールの構造を調べる。"],
          }),
        ],
      },
      {
        key: "future-physics",
        title: "物理学が築く未来",
        description: "量子技術、宇宙・重力波、材料、医療などへの物理学の応用を、成果と課題の両面から考えます。",
        lessons: [
          makeLesson({
            key: "physics-future",
            title: "物理学が築く未来",
            description: "物理学の成果が新しい科学技術の基盤となる具体例を調べます。",
            goals: ["先端物理と科学技術のつながりを具体例で説明できる。", "技術の可能性と限界・安全性を分けて考察できる。"],
            conceptTitle: "基礎研究の概念が長い時間を経て技術基盤になる",
            body: [
              "量子コンピュータ、光格子時計、核融合、重力波観測、ナノテクノロジー、加速器、医療画像などでは、これまで学んだ波・電磁気・量子・原子核の概念が利用されています。",
              "新技術を評価するときは、実現可能性、測定精度、エネルギー効率、安全性、社会的な利用条件を分けて検討します。",
            ],
            exampleProblem: "量子コンピュータが主に利用する物理分野を答える。",
            exampleSteps: [{ expression: "量子力学", note: "重ね合わせや量子状態の制御を計算へ利用します。" }],
            practiceProblem: "重力波観測が主に調べる対象として『時空』と『化学反応』のどちらが適切か。",
            practiceAnswers: ["時空"],
            practiceHint: "重力波は時空のゆがみの伝播です。",
            summary: ["物理学の基礎概念は科学技術の基盤になる。", "先端技術は有用性だけでなく限界・安全性・測定根拠も検討する。"],
          }),
        ],
      },
    ],
  },
];
